### ISSUE TITLE
Validate the container port

### ISSUE THREAD

**Issue by whitlockjc** [30x/k8s-router#12]
Whenever you route a host+path to a container port, we should make the extra effort to validate the container port is exposed in the pod.

**Comment by noahdietz** [comment]
How do you want to do this? It seems like low hanging fruit :) Is it possible to just check the pod spec if the `containerPort` property matches the `PORT` env var? or did you want to probe it?

**Comment by whitlockjc** [comment]
I think we should explicitly log the situation where your path contains a port that is not an exported container port.  It's a low-hanging fruit but I can see how this situation could be hard to debug without the proper information in the logs.

**Comment by noahdietz** [comment]
oh right, because you compare the port in the public/private path annotation to the contain port...if the annotation is incorrect do you log it and refuse to include it in the nginx conf? or do you fix it on the fly by routing to the container port (rather than the annotation port) and log the change?

**Comment by whitlockjc** [comment]
We would treat that pod as unroutable and log why.  This is the same approach we use elsewhere, like broken paths or what not.

**Comment by noahdietz** [comment]
Gotchya....I guess this is a conversation for a different issue thread, but how can the user find out if their route info is incorrect? if `k8s-router` just refuses to route and logs it, the user isn't notified, they just see errors from the Edge proxy that it isn't reachable. Is there a way we can expose this via an API or give some feedback `enrober`? It's non-trivial to debug from a user's perspective

**Comment by whitlockjc** [comment]
Exposing an API to track this could be cool.  I think the way `k8s-router` was written it didn't make sense to do this originally but I can see a case where this makes sense.  I'll create a separate issue for this.

**Comment by noahdietz** [comment]
Thanks for opening another issue, that would be fun to work on.....

I'm working on a change fort this issue right now. Not sure of a better way than looping over [containers/ports](https://gist.github.com/noahdietz/b04d80a7734972ef12794c5d4c77f8fc)...any other ideas?

**Comment by whitlockjc** [comment]
I've already got it done.
