### ISSUE TITLE
Remove environment variable resolution of Kubernetes

### ISSUE THREAD

**Issue by whitlockjc** [30x/k8s-router#45]
From day one we've had support for using the `KUBE_HOST` environment variable to point to your Kubernetes host.  The purpose was for testing and for running `k8s-router` outside of Kubernetes, typically for testing.  It would make more sense to use the built-in APIs for getting a Kubernetes client, which is how `kubectl` works, and this would allow you to point `k8s-router` to different clusters much easier.  Since `k8s-router` is a read-only tool, and its tests do not interact with your Kubernetes cluster, this should be pretty safe.

**Comment by whitlockjc** [comment]
The idea here is to use the same approach Kubernetes tools use to find the cluster client configuration.  Here is a good place to start: https://godoc.org/k8s.io/kubernetes/pkg/client/unversioned/clientcmd

**Comment by AdamMagaluk** [comment]
Great. Just to make sure i'm on the right path here. Normally you use KUBE_HOST=.. to set cluster ip for running outside cluster but only works with un-secure hosts. Instead we want to look at the kube config and get cluster ip and certs. And just tell k8s-router to run from local config.

**Comment by whitlockjc** [comment]
Right, and the code linked above is almost copy/paste ready.
