### ISSUE TITLE
Router does not pass through the host header correctly

### ISSUE THREAD

**Issue by mpnally** [30x/k8s-router#48]
The generated Nginx config has this line:

`proxy_set_header Host $host;`

In Nginx, the value of $host is the value of the incoming host header _**with the port number stripped off**_. Stripping off the port number is not the desired behavior. The line should be:

`proxy_set_header Host $http_host;`

**Comment by AdamMagaluk** [comment]
@mpnally Looks like Jeremy changed this on Sep 13. https://github.com/30x/k8s-router/commit/4c2def24326596848859e8bd9d43fa5b26de5b4a

Looks like something needs to be updated somewhere.

**Comment by mpnally** [comment]
That is interesting. As far a s I can tell, that change did not get deployed to e2e. Here is an excerpt from the log of a public router on E2E on 2016/10/26:

```
events {
  worker_connections 1024;
}
http {
  # http://nginx.org/en/docs/http/ngx_http_core_module.html
  types_hash_max_size 2048;
  server_names_hash_max_size 512;
  server_names_hash_bucket_size 64;

  # Force HTTP 1.1 for upstream requests
  proxy_http_version 1.1;

  # When nginx proxies to an upstream, the default value used for 'Connection' is 'close'.  We use this variable to do
  # the same thing so that whenever a 'Connection' header is in the request, the variable reflects the provided value
  # otherwise, it defaults to 'close'.  This is opposed to just using "proxy_set_header Connection $http_connection"
  # which would remove the 'Connection' header from the upstream request whenever the request does not contain a
  # 'Connection' header, which is a deviation from the nginx norm.
  map $http_connection $p_connection {
    default $http_connection;
    ''      close;
  }

  # Pass through the appropriate headers
  proxy_set_header Connection $p_connection;
  proxy_set_header Host $host;
  proxy_set_header Upgrade $http_upgrade;

```

**Comment by AdamMagaluk** [comment]
Do we know what version is deployed to e2e and what code commit/tag that Docker image was built from?

This I found to be an issue in the past when you manually create Docker images from your laptop for use in production. It's hard to map what was actually used to create the image. On the Link team we moved all our Docker images to auto builds based on github commits and tags so there would always be a reliable mapping.

**Comment by mpnally** [comment]
Yes, indeed. We need to get onto a proper process for deployment. I think there is already and issue for this. Mamu/Jordan have already defined a process with tools—we need to use it.

**Comment by whitlockjc** [comment]
`k8s-router` is already using `$http_host` instead of `$host`: https://github.com/30x/k8s-router/blob/master/nginx/config.go#L77  And this should be deployed to both e2e and prod.  I will do some digging.

As for the labeling of Docker builds against the git revision, we can do that.
