### ISSUE TITLE
Router limiting upload size

### ISSUE THREAD

**Issue by noahdietz** [30x/k8s-router#51]
`kiln` allows an upload size of 100MB (this may or may not be _way_ too big, but thats not the problem).

A user tried to upload a zip of size 5MB. It was rejected with `413 Request Entity too large` from an `nginx` server (I'm guessing the router).

We need to increase `client_max_body_size` (docs [here](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size)) in the `nginx-conf`.

**Comment by whitlockjc** [comment]
I'm not sure I agree with #52.  Would it had been simpler to just turn off body size checking and let the application itself, like `kiln`, do the checking?  It seems we'll be chasing our tails trying to guess so why not just remove the guessing?
